# Generated by Django 4.1.1 on 2023-08-31 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
